export const ONFORMTITLECHANGE = "ONFORMTITLECHANGE";

//SECTION ACTOIN TYPES
export const ONSECTIONCHANGE = "ONSECTIONCHANGE";
export const ONSECTIONADD = "ONSECTIONADD";
export const ONSECTIONREMOVE = "ONSECTIONREMOVE";

//QUESTION ACTION TYPES
export const ONQUESTIONADD = "ONQUESTIONADD";
export const ONQUESTIONCHNAGE = "ONQUESTIONCHNAGE";
export const ONQUESTIONREMOVE = "ONQUESTIONREMOVE";

//OPTIONS ACTION TYPES
export const ONOPTIONADD = "ONOPTIONADD";
export const ONOPTIONCHNAGE = "ONOPTIONCHNAGE";
export const ONOPTIONREMOVE = "ONOPTIONREMOVE";

// export const ONFORMSUBMIT = "ONFORMSUBMIT";
